POST http://localhost:5001/api/auth/register
Content-Type: application/json


{
    "email": "rritesh@gmail.com",
    "password": "rk",
    "phone":7878787878,
    "name": "ritesh"
}

###
POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
    "email": "rritesh@gmail.com",
    "password": "rk"
}